In [ ]:
import numpy as np
import matplotlib.pyplot as plt

### Exercise



Use k-fold cross-validation to estimate the performance of a MLPRegressor on the `wine_quality_white` dataset. Use a single hidden layer.

In [35]:
from sklearn.datasets import fetch_openml
w = fetch_openml(name='wine-quality-white',version=1, parser='auto')

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(w.data.to_numpy(), 
                                                    w.target.to_numpy().astype(int), 
                                                    random_state=0)


In [37]:
y_train

array([4, 5, 4, ..., 4, 4, 3])

In [38]:
from sklearn.neural_network import MLPRegressor

# start with the untrained model
nn = MLPRegressor(hidden_layer_sizes=(10),max_iter=10000)

# a 5-fold cross-validation, scored using r2
score = cross_val_score( nn, 
                         X_train, 
                         y_train,
                         cv=5,
                         scoring='r2' )
print("Cross-validated r2:")
print(score)

Cross-validated r2:
[0.23260797 0.2997482  0.26645055 0.1776276  0.30358128]


In [39]:
score.mean()

0.2560031201320774

Does adding a second hidden layer appear to improve performance?

In [40]:
nn2 = MLPRegressor(hidden_layer_sizes=(10,10),max_iter=10000)

# a 5-fold cross-validation, scored using r2
score = cross_val_score( nn2, 
                         X_train, 
                         y_train,
                         cv=5,
                         scoring='r2' )
print("Cross-validated r2:")
print(score)

Cross-validated r2:
[0.26617367 0.23323672 0.27988142 0.2022865  0.31351629]


In [41]:
score.mean()

0.25901891914048625

In [42]:
score.std()

0.03831367146680027

The `ilpd` dataset contains data from 416 liver patient records (class 1) and 167 non liver patient records (class 2). Plot a cross-validated ROC curve for a random forest classifier on these data.

In [ ]:
ilpd = fetch_openml(name='ilpd', version=1, parser='auto')

In [ ]:
ilpd.data.head()

In [ ]:
ilpd.target.head()